### ISSUE TITLE
match() instead of switch()

### ISSUE THREAD

**Issue by TheDigitalOrchard** [wind-framework/wind-framework#6]
https://github.com/wind-framework/wind-framework/blob/a1431f7d4e2145786b06d19ef1e94abf399e56e6/src/base/Application.php#L120

The `match()` construct is a great candidate for replacing this `switch()` statement:

```php

return match($type) {
    E_ERROR => 'E_ERROR',
    E_WARNING => 'E_WARNING,
    // etc.
    default    => ''
};

```

**Comment by xpader** [comment]
Thank you for you suggestion, for old version of wind-framework, I need consider compatble of old php version 7.2.5, but in wind-framework 1.0, it's already updated https://github.com/wind-framework/wind-framework/commit/9c0af88215b36e4af9dc375fd5a92847e0c23805.

**Comment by anoxia** [comment]
> https://github.com/wind-framework/wind-framework/blob/a1431f7d4e2145786b06d19ef1e94abf399e56e6/src/base/Application.php#L120
> 
> The `match()` construct is a great candidate for replacing this `switch()` statement:
> 
> ```
> return match($type) {
>     E_ERROR => 'E_ERROR',
>     E_WARNING => 'E_WARNING,
>     // etc.
>     default    => ''
> };
> ```

`match` does not perform better than `switch`, it simply make the code cleaner, for low-level library `switch` should be preferred. 😊
